[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG = "INFO"
ESP_WIFI_CONFIG_MAX_BURST_SIZE = "8"
TROUBLE_HOST_L2CAP_RX_QUEUE_SIZE = "4"

[build]
rustflags = [
    "-C", "link-arg=-nostartfiles",
    # See <https://docs.rs/esp-wifi/latest/esp_wifi/>
    "-C", "link-arg=-Tlinkall.x",
]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]
